Create hash_map
mcnckc/HashMap pull request #1
Opened 2021-03-04 12:19 UTC by mcnckc

2021-03-04 12:47 UTC, mcnckc commented
201 Михаил Гусев, контест 3, задача A, https://official.contest.yandex.ru/contest/24924/run-report/48646051/

2021-06-13 22:35 UTC, glebshp requested changes

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +//HashTable with chain method, elements are stored in std::vector. Doubles array size when load excesses half of array size. If load factor is less than 1/8 array size is twice derceased.
Очень длинная строчка.

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +//HashTable with chain method, elements are stored in std::vector. Doubles array size when load excesses half of array size. If load factor is less than 1/8 array size is twice derceased.
Не хватает ссылки на более подробное описание реализации (например, на википедию)

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +    constexpr size_t maxload = 2, minload = 8;
вынести в разные строки

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +        if(amount * maxload <= table.size() && amount * minload >= table.size()) return;
сделать return на отдельной строке, использовать фигурные скобки

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +    void rehash() {
функция не всегда делает rehash, а только если выполняется условие, сделать название более отражающим этот функционал

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +    constexpr size_t maxload = 2, minload = 8;
а почему вообще maxload = 2, зачем нам перестраивать таблицу если она заполнена только наполовину?

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +        size_t nsz = (amount * maxload > table.size() ? 2 * table.size() : (table.size() + 1) / 2);
неприятный для чтения тернарный оператор, заменить на if

2021-06-13 22:35 UTC, glebshp commented on hash_map
> + private:
у класса сначала идёт интерфейс - публичные методы, приватные поля в конце

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +    size_t amount = 0;
amount используется для сущностей, которые нельзя перечислить, amount of water например, для количества quantity или size или number

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +            for(value_type x : other.table[id]) {
а чего не const?

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +            ++amount, ++tf;
одна строка - одно действие

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +        table.resize(2 * amount);
управляющая константа, есть вынесенная отдельно

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +            table[id].push_back(*first++);
одна строка - одна действие

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +            size_t id = hasher(first->first) % table.size();
такой себе нейминг получается, лучше first_element

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +        table.resize(2 * l.size());
опять же константа в коде

2021-06-13 22:35 UTC, glebshp commented on hash_map
> +            for(size_t i = table[id].size() - 1; i > pos; --i) {
вычитание знакового из беззнакового

2021-06-19 15:33 UTC, glebshp requested changes

2021-06-19 15:33 UTC, glebshp commented on README.md
> +201 Михаил Гусев, контест 3, задача A, https://official.contest.yandex.ru/contest/24924/run-report/48646051/
обойдёмся без кириллицы

2021-06-24 21:46 UTC, glebshp requested changes
Слишком мало пояснений о том как работает таблица, чтобы её можно было нормально проверить

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    //method used to find specific key in the chain. Returns position if found, chain size otherwise. O(chain_length).
не хватает пустой строки

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    constexpr static size_t maxload = 1;
константы должны быть public, по стилю оформления должны отличаться от полей и методов

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    constexpr static size_t minload = 8;
не хватает размера масштабирования как настраиваемого параметра

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    //make this table empty.
Здесь и всюду не хватает пустых строк между концом одного метода и началом комментария к другому

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    const_iterator begin() const {
везде не хватает пустых строк между методами

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +        return iterator(table.begin() + table.size() - 1, table.begin() + table.size() - 1, (table.begin() + table.size() - 1)->end());
что это за страшные выражения, откуда они взялись? чем не подошёл итератор .end() ?

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +//Iterator class, to iterate through HashMap, made with builtin iterators to container which is used in HashMap realisation.
Очень скудное описание класса. Должно быть описание принципа реализации, указание на то как осуществляется масштабирование, почему будет линейное итерирование, ссылка на источник с подробным описанием алгоритма (например, на википедию)

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    Iterator(typename vector<vector<value_type>>::iterator _id, typename vector<vector<value_type>>::iterator _last, typename vector<value_type>::iterator _pos) : id(_id), last(_last), pos(_pos) {
строка не влезает в экран

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +            ++id, pos = id->begin();
давай делать одно действие в одной строке

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +        if(id == last && pos == id->end()) return *this;
скобки, не надо однострочный if

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    //Increment, makes iterator point to the next element and return it's new version. O(1) amortisated.
it's -> its

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +    //Increment, makes iterator point to the next element and return it's new version. O(1) amortisated.
и слово "амортизировано" пишет не так

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +            nsz = 2 * table.size();
константа 2 в коде

2021-06-24 21:46 UTC, glebshp commented on hash_map.h
> +        iterator it = find(key);
мы тут аж три раза сделаем сканирование на одну операцию, в худшем случае два раза на find и один на instert, а можно ведь обойтись одним (кроме случая, когда придётся перестраивать таблицу)

2021-06-25 18:35 UTC, glebshp approved these changes
сойдёт

2021-06-25 19:18 UTC, merged